/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package payrollproject;

import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
/**
 *
 * @author 18764
 */
public class CRUD_GUI extends javax.swing.JFrame {

    /**
     * Creates new form CRUD_GUI
     */
    public CRUD_GUI() {
        initComponents();
        connect ();
    }
    Connection conn;
    
    PreparedStatement state;
               
            
    public void connect ()
    {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("","",""); //insert database URL, username, password
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CRUD_GUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CRUD_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_payrollapp = new javax.swing.JPanel();
        label_employeeID = new javax.swing.JLabel();
        label_fname = new javax.swing.JLabel();
        label_mname = new javax.swing.JLabel();
        label_lname = new javax.swing.JLabel();
        label_dob = new javax.swing.JLabel();
        label_contact = new javax.swing.JLabel();
        label_status = new javax.swing.JLabel();
        label_address = new javax.swing.JLabel();
        textfield_fname = new javax.swing.JTextField();
        textfield_mname = new javax.swing.JTextField();
        textfield_lname = new javax.swing.JTextField();
        textfield_dob = new javax.swing.JTextField();
        textfield_status = new javax.swing.JTextField();
        textfield_address = new javax.swing.JTextField();
        textfield_contact = new javax.swing.JTextField();
        combobox_empID = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        btn_add = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_search = new javax.swing.JButton();
        label_payrollapp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_payrollapp.setBorder(javax.swing.BorderFactory.createTitledBorder("Employee Details"));

        label_employeeID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label_employeeID.setText("Employee ID:");

        label_fname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label_fname.setText("First Name:");

        label_mname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label_mname.setText("Middle Name:");

        label_lname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label_lname.setText("Last Name:");

        label_dob.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label_dob.setText("D.O.B.:");

        label_contact.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label_contact.setText("Contact #:");

        label_status.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label_status.setText("Status:");

        label_address.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label_address.setText("Address:");

        btn_add.setText("Add Record");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_update.setText("Update Record");

        btn_delete.setText("Delete Record");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_add)
                .addGap(29, 29, 29)
                .addComponent(btn_update)
                .addGap(31, 31, 31)
                .addComponent(btn_delete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_delete)
                    .addComponent(btn_update)
                    .addComponent(btn_add))
                .addContainerGap())
        );

        btn_search.setText("Search");

        javax.swing.GroupLayout panel_payrollappLayout = new javax.swing.GroupLayout(panel_payrollapp);
        panel_payrollapp.setLayout(panel_payrollappLayout);
        panel_payrollappLayout.setHorizontalGroup(
            panel_payrollappLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_payrollappLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_payrollappLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panel_payrollappLayout.createSequentialGroup()
                        .addComponent(label_employeeID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(combobox_empID, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_payrollappLayout.createSequentialGroup()
                        .addGroup(panel_payrollappLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_fname)
                            .addComponent(label_mname)
                            .addComponent(label_lname)
                            .addComponent(label_dob))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel_payrollappLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textfield_dob, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textfield_lname, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textfield_mname, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textfield_fname, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btn_search))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(panel_payrollappLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_contact)
                    .addComponent(label_address)
                    .addComponent(label_status))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(panel_payrollappLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textfield_contact, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfield_status, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfield_address, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_payrollappLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133))
        );
        panel_payrollappLayout.setVerticalGroup(
            panel_payrollappLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_payrollappLayout.createSequentialGroup()
                .addGroup(panel_payrollappLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_contact)
                    .addComponent(textfield_contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combobox_empID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_employeeID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_search)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_payrollappLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_fname)
                    .addComponent(label_status)
                    .addComponent(textfield_fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfield_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_payrollappLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_payrollappLayout.createSequentialGroup()
                        .addGroup(panel_payrollappLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_mname)
                            .addGroup(panel_payrollappLayout.createSequentialGroup()
                                .addComponent(textfield_mname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(panel_payrollappLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textfield_lname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label_lname))
                                .addGap(18, 18, 18)
                                .addGroup(panel_payrollappLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textfield_dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label_dob)))
                            .addComponent(textfield_address, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(panel_payrollappLayout.createSequentialGroup()
                        .addComponent(label_address)
                        .addGap(42, 42, 42)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        label_payrollapp.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        label_payrollapp.setText("Payroll Application");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(label_payrollapp))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(panel_payrollapp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_payrollapp)
                .addGap(18, 18, 18)
                .addComponent(panel_payrollapp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
        
       /* String fname = textfield_fname.getText();
        String mname = textfield_mname.getText();
        String lname = textfield_lname.getText();
        String dob = textfield_dob.getText();
        String status = textfield_status.getText();
        String contact = textfield_contact.getText();
        String address = textfield_address.getText();
        
        state = conn.prepareStatement ("insert into **tablename(c1, c2, c3, c4, c5, c6, c7)values(?,?,?,?,?,?,?"); //input table name and column names
        state.setString(1, fname);
        state.setString(2, mname);
        state.setString(3, lname);
        state.setString(4, dob);
        state.setString(5, status);
        state.setString(6, contact);
        state.setString(7, address);*/
    }//GEN-LAST:event_btn_addActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUD_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUD_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUD_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUD_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CRUD_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_search;
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox<String> combobox_empID;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_address;
    private javax.swing.JLabel label_contact;
    private javax.swing.JLabel label_dob;
    private javax.swing.JLabel label_employeeID;
    private javax.swing.JLabel label_fname;
    private javax.swing.JLabel label_lname;
    private javax.swing.JLabel label_mname;
    private javax.swing.JLabel label_payrollapp;
    private javax.swing.JLabel label_status;
    private javax.swing.JPanel panel_payrollapp;
    private javax.swing.JTextField textfield_address;
    private javax.swing.JTextField textfield_contact;
    private javax.swing.JTextField textfield_dob;
    private javax.swing.JTextField textfield_fname;
    private javax.swing.JTextField textfield_lname;
    private javax.swing.JTextField textfield_mname;
    private javax.swing.JTextField textfield_status;
    // End of variables declaration//GEN-END:variables
}
